title: Shane's technical writing guidelines for AI
description: This website is Shane's subjective technical writing preferences collected in one place for use with AI.
theme: just-the-docs

url: https://sloretz.github.io/Shanes-technical-writing-guidelines-for-AI

aux_links: # remove if you don't want this link to appear on your pages
  Github Repository: https://github.com/sloretz/Shanes-technical-writing-guidelines-for-AI

color_scheme: shane
logo: "/assets/images/stwga_logo.png"

exclude:
  - AGENTS.md
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .github
  - .vscode
  - .devcontainer
  - vendor
  